@contentType = application/json
POST http://localhost:5000/api/auth/login
Content-Type: {{contentType}}

{
    "username": "Erwan",
    "password": "Thomas64"
}


### 
GET http://localhost:5000/api/comments

###
GET http://localhost:5000/api/auth/logout

###

DELETE http://localhost:5000/api/users/7c5c2914-da72-4fd8-83cc-2a3a52eefbce


###

PUT http://localhost:5000/api/users/054579b5-233f-4c32-aee8-5165392b912b
Content-Type: application/json

{
    "landimageUrl": "https://images.unsplash.com/photo-1599725055007-b33b6755ef6f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1329&q=80"
}
