GET  http://localhost:5000/post

###
GET http://localhost:5000/post/13d27728-546b-46d5-a05d-f265797dea66

###
GET http://localhost:5000/post/user/78cbcaf6-8969-45e8-884a-1d3fadac30a0

###
@contentType = application/json
POST http://localhost:5000/post
Content-Type: {{contentType}}

{
    "title": "PostTest5",
    "text": " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eu facilisis sem. Vivamus eu facilisis sem.",
    "imageUrl": "https://images.unsplash.com/photo-1599725055007-b33b6755ef6f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1029&q=80",
    "userId": "a4ff96ab-458f-4c1d-a841-8a5619938890"
}

###

@contentType = application/json
PUT http://localhost:5000/post/13d27728-546b-46d5-a05d-f265797dea66
Content-Type: {{contentType}}

{
    "title": "PostTest1",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eu facilisis sem. Vivamus eu facilisis sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eu facilisis sem. Vivamus eu facilisis sem.",
    "imageUrl": "https://images.unsplash.com/photo-1599725055007-b33b6755ef6f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1029&q=80"
}

###

DELETE http://localhost:5000/post/cb4d785e-a737-4221-adbd-45bb0864cbc2
