GET http://localhost:5000/api/users  HTTP/1.1

###

GET http://localhost:5000/api/users/4e2c4d9b-8e94-4e00-86ca-cc64dc469e42 HTTP/1.1

###
@contentType = application/json
POST http://localhost:5000/api/users
Content-Type: {{contentType}}

{
    "username": "User3",
    "profilTitle": "développeur",
    "email": "User3@gmail.com",
    "password": "12345",
    "city": "Paris",
    "birthDate": "06/10/95",
    "avatarUrl": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80",
    "landimageUrl": "https://images.unsplash.com/photo-1599725055007-b33b6755ef6f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1329&q=80",
    "idFormation": "a9fb9f6a-dafb-4ade-b244-784678e5a765"
}

###
GET http://localhost:5000/api/users/78cbcaf6-8969-45e8-884a-1d3fadac30a0/skills

###
PUT http://localhost:5000/api/users/85fdd6a9-025b-477e-8a36-743f1f61103e
Content-Type: application/json

{
    "username": "UserTest5",
    "email": "userUserTest5@gmail.com",
    "city": "Pau",
    "birthDate": "25/05/2000",
    "avatarUrl": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80",
    "landimageUrl": "https://images.unsplash.com/photo-1599725055007-b33b6755ef6f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1329&q=80"
}

###

DELETE http://localhost:5000/api/users/7c5c2914-da72-4fd8-83cc-2a3a52eefbce


7c5c2914-da72-4fd8-83cc-2a3a52eefbce

39a541a9-eb91-463b-ad40-a5108f736a38

d6cda01c-9977-4059-8604-2de150bbf7c8
###

PUT http://localhost:5000/api/users/054579b5-233f-4c32-aee8-5165392b912b
Content-Type: application/json

{
    "landimageUrl": "https://images.unsplash.com/photo-1599725055007-b33b6755ef6f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1329&q=80"
}
