
###
// receive a Array of skills from a UserId 
GET http://localhost:5000/api/userskills/7c5c2914-da72-4fd8-83cc-2a3a52eefbce

###

GET http://localhost:5000/api/userskills/oneskill/9d8cc326-7aaf-4107-aac1-75180a753bb6

###
@contentType = application/json
POST http://localhost:5000/api/userskills
Content-Type: {{contentType}}

{
   "userId": "4e2c4d9b-8e94-4e00-86ca-cc64dc469e42",
   "skillId": "47efb44f-999c-4fe3-9f9a-0c70c1619b40",
   "note": 7
}

###
@contentType = application/json
PUT http://localhost:5000/api/userskills/fa4ae659-76ca-4aa1-8c82-558c91ec88f7
Content-Type: {{contentType}}

{
   "skillId": "0aa26e2a-63de-4502-8377-c8840596f236",
   "note": 8
}

###

DELETE http://localhost:5000/api/userskills/fa4ae659-76ca-4aa1-8c82-558c91ec88f7